### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by jpope777** [marekjm/diaspy#17]
I have my pod running the latest D* develop, as of about a week ago, diaspy has quit posting for me which was working beautifully prior.

Here is the traceback that I get when attempting to post:

    Traceback (most recent call last):
      File "/home/jpope/bin/diaspost", line 7, in <module>
        password='[redacted]')
      File "/usr/lib/python3.4/site-packages/diaspy-0.4.2-py3.4.egg/diaspy/connection.py", line 48, in __init__
      File "/usr/lib/python3.4/site-packages/diaspy-0.4.2-py3.4.egg/diaspy/connection.py", line 184, in _fetchtoken
    AttributeError: 'NoneType' object has no attribute 'group'

**Comment by marekjm** [comment]
Sorry for slow response. I'll try to fix it (weekend, yay!).

**Comment by jpope777** [comment]
Commit 5408fc4 seems to have fixed the issue for me, thanks man!

**Comment by marekjm** [comment]
You're welcome.

**Comment by vindarel** [comment]
Hi there ! The fix didn't get to pypi, but I'm facing this bug (because I want to try @jpope777 's script for desktop notifications !). When will it be available ?

I'm using version 3.0. 

thanks !

**Comment by marekjm** [comment]
Hi @vindarel.

Could you upgrade to the lastest code manually using Git for now?

**Comment by vindarel** [comment]
Yes I could, but I'm not interested right now :D I'd like to distribute a script, so I really need a fixed version on pypi.

**Comment by vindarel** [comment]
So, do you have plans to update the pypi package in a near future ? Thanks !

**Comment by marekjm** [comment]
If there's demand, there should be supply... I will put `diaspy` on PyPI during the weekend (or maybe earlier, but don't count on it).

**Comment by marekjm** [comment]
gg

**Comment by vindarel** [comment]
Cool :) this week-end would be really OK.

**Comment by marekjm** [comment]
Diaspy should be installable from PyPI now: https://pypi.python.org/pypi/diaspy-api/

**Comment by vindarel** [comment]
Thank you ! It works very well now. I'll keep you updated if I come up with a nice package (it's [nothing fancy atm](https://gitlab.com/vindarel/diaspora-notify)).

**Comment by marekjm** [comment]
Cool, good to know it's working.

Also, sure thing, keep me updated but I'd rather not turn this thread into a chat. Feel free to open new issue (when something new pops up) or find me on Diaspora\*: [marekjm@iliketoast.net](https://iliketoast.net/people/c08c71b06060e97b)

**Comment by deadtom76** [comment]
Hello. First time posting about a bug, so I'm not sure what all you need, but this does seem to be the same issue as the OP here. I'm seeing this on Python 3.6.6, and 3.5.2, but it seems to work fine in 3.6.2.

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/diaspy/connection.py", line 42, in __init__
    self._setlogin(username, password)
  File "/usr/local/lib/python3.6/site-packages/diaspy/connection.py", line 116, in _setlogin
    'authenticity_token': self._fetchtoken()}
  File "/usr/local/lib/python3.6/site-packages/diaspy/connection.py", line 166, in _fetchtoken
    token = self._token_regex.search(request.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group''`

Let me know if you need any other information, or if it's something simple on my end.
Thanks!

**Comment by CYBERDEViLNL** [comment]
I suspect you are using a old version of diaspy. Please update to the latest master branch.

**Comment by deadtom76** [comment]
It's whatever version is available from PIPY. I'll manually upgrade though, and see how it goes. Thanks!

**Comment by deadtom76** [comment]
Unfortunately, this did not resolve the issue. Same result.

**Comment by CYBERDEViLNL** [comment]
If you get the exact same message it's very strange since the linenumbers in your message don't match with the current master branch. Did you remove the old version?

**Comment by deadtom76** [comment]
> If you get the exact same message it's very strange since the linenumbers in your message don't match with the current master branch. Did you remove the old version?

Ah, there was the problem. I removed the old one, installed this one again, all good now.

Thanks so much!
