### ISSUE TITLE
Python 3 - Error on initialization

### ISSUE THREAD

**Issue by balasankarc** [marekjm/diaspy#26]
Hi,

I was using diaspy with Python 2.7 . After the discussion from last issue ( #25 ) , I wanted to try out Python 3. But, I am getting the following error

\>>> c = diaspy.connection.Connection(pod='\<my pod here>', username='\<my username>', password='\<my password>')
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/diaspy/connection.py", line 42, in __init__
    self._setlogin(username, password)
  File "/usr/local/lib/python3.4/dist-packages/diaspy/connection.py", line 116, in _setlogin
    'authenticity_token': self._fetchtoken()}
  File "/usr/local/lib/python3.4/dist-packages/diaspy/connection.py", line 166, in _fetchtoken
    token = self._token_regex.search(request.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/diaspy/connection.py", line 44, in __init__
    raise LoginError('cannot create login data (caused by: {0}'.format(e))
diaspy.connection.LoginError: cannot create login data (caused by: 'NoneType' object has no attribute 'group'

It was working fine with Python 2.7. Any idea what went wrong with Python 3? Thanks.

**Comment by marekjm** [comment]
It seems something's wrong with the `_token_regex` regular expression as it couldn't find the token in text it got from Diaspora.

**Comment by mantonelli** [comment]
Same problem here!

I've tried with Python 2.7.5 and Python 3.4.3, on pods https://diasporabrazil.org and https://therealtalk.org.

I'm using diasy 0.3.0, installed with pip.

Thanks!

**Comment by marekjm** [comment]
I'm closing this issue since new version is available on PyPI. Install [`diaspy-api`](https://pypi.python.org/pypi/diaspy-api/0.5.1).

If the bug is still there, please reopen the issue.
